services:
  debugger:
    build: ./containers/debugger
    depends_on:
      - redis-server
    environment:
      REDIS_SERVER: "redis://redis-server:6379"
  emtransformer:
    build: ./containers/emtransformer
    depends_on:
      - redis-server
    environment:
      REDIS_SERVER: "redis://redis-server:6379"
  redis-server:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
