name: ZeroER
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=21.0.1
  - python=3.6.12
  - setuptools=52.0.0
  - tk=8.6.10
  - pip:
    - backcall==0.2.0
    - chardet==4.0.0
    - cloudpickle==1.6.0
    - cycler==0.10.0
    - decorator==4.4.2
    - idna==2.10
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - joblib==1.0.1
    - kiwisolver==1.3.1
    - matplotlib==3.3.4
    - numpy==1.19.5
    - pandas==1.1.5
    - parso==0.8.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.1.0
    - prompt-toolkit==3.0.16
    - ptyprocess==0.7.0
    - py-entitymatching==0.4.0
    - py-stringmatching==0.4.2
    - py-stringsimjoin==0.3.2
    - pygments==2.8.0
    - pyparsing==2.4.7
    - pyprind==2.11.2
    - python-dateutil==2.8.1
    - pytz==2021.1
    - requests==2.25.1
    - scikit-learn==0.24.1
    - scipy==1.5.4
    - six==1.15.0
    - threadpoolctl==2.1.0
    - tqdm==4.57.0
    - traitlets==4.3.3
    - urllib3==1.26.3
    - wcwidth==0.2.5